[linters]
enable = [
  'errcheck',
  'gocritic',
  'goimports',
  'gosec',
  'gosimple',
  'govet',
  'ineffassign',
  'lll',
  'misspell',
  'nakedret',
  'scopelint',
  'staticcheck',
  'structcheck',
  'stylecheck',
  'typecheck',
  'unconvert',
  'unparam',
  'unused',
  'varcheck',
  'whitespace',
]

[linters-settings.lll]
line-length = 100

